name: flutter_server
description: A Dart server for Flutter demo
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  shelf_cors_headers: ^0.1.5
